"""Structural health of the vault.

Checks (schema: Operations > Lint): broken wikilinks, orphans, duplicate note names,
schema coverage (`type` / `data_asof` / `summary`), and data-bearing pages past their
`data_asof` clock. Must report 0 broken and 0 orphans. Regenerates `_Brain Health.md`.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from datetime import date
from pathlib import Path

from gms.brain import vault

HEALTH_PAGE = "_Brain Health.md"


@dataclass
class Report:
    today: str
    pages: int
    broken: list[dict] = field(default_factory=list)
    missing_assets: list[dict] = field(default_factory=list)
    orphans: list[str] = field(default_factory=list)
    duplicates: list[str] = field(default_factory=list)
    missing_fields: dict[str, list[str]] = field(default_factory=dict)
    bad_types: list[dict] = field(default_factory=list)
    stale: list[dict] = field(default_factory=list)
    inbound: dict[str, int] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not self.broken and not self.orphans and not self.duplicates

    def to_json(self) -> str:
        d = asdict(self)
        d["ok"] = self.ok
        return json.dumps(d, indent=2, ensure_ascii=False)


def parse_asof(value: str | None) -> date | None:
    """`YYYY-MM-DD` or `YYYY-MM` (read as month-end is too generous; use the 1st)."""
    if not value or value == "n/a":
        return None
    parts = value.strip().split("-")
    try:
        if len(parts) >= 3:
            return date(int(parts[0]), int(parts[1]), int(parts[2][:2]))
        if len(parts) == 2:
            return date(int(parts[0]), int(parts[1]), 1)
    except ValueError:
        return None
    return None


def run(brain: Path, today: date | None = None) -> Report:
    today = today or date.today()
    pages = vault.load(brain)
    names = vault.resolver(pages)
    rep = Report(today=today.isoformat(), pages=len(pages))

    counts = Counter(k.split("\x00", 1)[0] for k in pages)
    rep.duplicates = sorted(n for n, c in counts.items() if c > 1)

    inbound: dict[str, set[str]] = defaultdict(set)
    for key, page in pages.items():
        src = key.split("\x00", 1)[0]
        for target in page.links:
            hit = vault.resolve(target, names)
            if hit:
                if hit != src and src not in vault.GENERATED:
                    inbound[hit].add(src)
            elif vault.is_asset(target):
                # Binary deliverables (html/docx/pdf/...) are built outside the repo.
                rep.missing_assets.append({"page": src, "target": target})
            else:
                rep.broken.append({"page": src, "target": target})

    rep.inbound = {k.split("\x00", 1)[0]: len(inbound.get(k.split("\x00", 1)[0], ())) for k in pages}
    rep.orphans = sorted(n for n, c in rep.inbound.items() if c == 0 and n not in vault.ROOTS)

    missing: dict[str, list[str]] = {"type": [], "data_asof": [], "summary": []}
    for key, page in pages.items():
        name = key.split("\x00", 1)[0]
        for f in missing:
            if page.meta.get(f) in (None, ""):
                missing[f].append(name)
        if page.type and page.type not in vault.PAGE_TYPES:
            rep.bad_types.append({"page": name, "type": page.type})
        clock = vault.CLOCKS.get(page.type or "")
        if clock:
            asof = parse_asof(page.data_asof)
            if asof is None:
                rep.stale.append({"page": name, "type": page.type, "data_asof": page.data_asof, "age_days": None, "limit": clock})
            elif (today - asof).days > clock:
                rep.stale.append({"page": name, "type": page.type, "data_asof": page.data_asof,
                                  "age_days": (today - asof).days, "limit": clock})
    rep.missing_fields = {k: sorted(v) for k, v in missing.items() if v}
    rep.stale.sort(key=lambda s: -(s["age_days"] or 10**6))
    return rep


def health_page(rep: Report) -> str:
    top = sorted(rep.inbound.items(), key=lambda kv: -kv[1])[:10]
    weak = sorted((kv for kv in rep.inbound.items() if kv[0] not in vault.ROOTS), key=lambda kv: kv[1])[:10]
    lines = [
        "---",
        "title: _Brain Health",
        "category: meta",
        "type: meta",
        "data_asof: n/a",
        f'summary: "Auto-generated by gms lint on {rep.today}: {rep.pages} pages, {len(rep.broken)} broken links, '
        f'{len(rep.orphans)} orphans, {len(rep.stale)} pages past their data_asof clock."',
        "tags: [meta, health, lint]",
        'data_vintage: "generated — do not edit by hand"',
        "sources: 0",
        f"updated: {rep.today}",
        "---",
        "",
        "# _Brain Health",
        "",
        f"Generated by `python -m gms lint` on **{rep.today}**. Do not edit — rerun lint. Schema: [[_Vault Schema & Conventions]] · catalog: [[index]] · history: [[log]].",
        "",
        "| Check | Result |",
        "|---|---|",
        f"| Pages | {rep.pages} |",
        f"| Broken wikilinks | {len(rep.broken)} |",
        f"| Orphans (zero inbound) | {len(rep.orphans)} |",
        f"| Duplicate note names | {len(rep.duplicates)} |",
        f"| Links to binary deliverables not in repo | {len(rep.missing_assets)} |",
        f"| Missing `type` / `data_asof` / `summary` | "
        f"{len(rep.missing_fields.get('type', []))} / {len(rep.missing_fields.get('data_asof', []))} / {len(rep.missing_fields.get('summary', []))} |",
        f"| Past data_asof clock | {len(rep.stale)} |",
        "",
    ]
    if rep.broken:
        lines += ["## Broken links", "", "| Page | Target |", "|---|---|"]
        lines += [f"| {b['page']} | `{b['target']}` |" for b in rep.broken]
        lines.append("")
    if rep.orphans:
        lines += ["## Orphans", ""] + [f"- `{o}`" for o in rep.orphans] + [""]
    if rep.stale:
        lines += ["## Past their data clock", "", "| Page | Type | data_asof | Age (days) | Limit |", "|---|---|---|---|---|"]
        lines += [f"| {s['page']} | {s['type']} | {s['data_asof']} | {s['age_days'] if s['age_days'] is not None else 'unparseable'} | {s['limit']} |"
                  for s in rep.stale]
        lines.append("")
    lines += ["## Hubs (most inbound)", "", "| Page | Inbound |", "|---|---|"]
    lines += [f"| {n} | {c} |" for n, c in top]
    lines += ["", "## Weakest nodes (cross-linking candidates)", "", "| Page | Inbound |", "|---|---|"]
    lines += [f"| {n} | {c} |" for n, c in weak]
    lines.append("")
    return "\n".join(lines)


def main(brain: Path, write: bool = True, today: date | None = None) -> Report:
    rep = run(brain, today)
    if write:
        (brain / "00 - Home" / HEALTH_PAGE).write_text(health_page(rep), encoding="utf-8")
    return rep
