"""Regenerate the vault catalog from page frontmatter.

Writes `00 - Home/index.md` (one table per folder, then a view by type) and
`00 - Home/brain_index.json`. Gated: refuses to write if fewer than 90% of pages
carry a `summary`, so a half-migrated vault can't overwrite a good catalog.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import date
from pathlib import Path

from gms.brain import vault

SUMMARY_GATE = 0.90
SKIP = {"index"}


class GateError(RuntimeError):
    pass


def _cell(text: str | None) -> str:
    return (text or "—").replace("|", "\\|").replace("\n", " ").strip()


def _link(name: str) -> str:
    return f"[[{name}]]".replace("|", "\\|")


def build(brain: Path, today: date | None = None) -> tuple[str, list[dict]]:
    today = today or date.today()
    pages = [p for k, p in vault.load(brain).items() if p.name not in SKIP]
    with_summary = sum(1 for p in pages if p.summary)
    if pages and with_summary / len(pages) < SUMMARY_GATE:
        raise GateError(f"only {with_summary}/{len(pages)} pages carry a summary (< {SUMMARY_GATE:.0%}); fix frontmatter first")

    by_folder: dict[str, list[vault.Page]] = defaultdict(list)
    by_type: dict[str, list[vault.Page]] = defaultdict(list)
    for p in pages:
        by_folder[p.folder or "(root)"].append(p)
        by_type[p.type or "(untyped)"].append(p)

    lines = [
        "---",
        "title: index",
        "category: meta",
        "type: meta",
        "data_asof: n/a",
        f'summary: "Generated catalog of all {len(pages)} pages — one table per folder plus a view by type; rebuilt from frontmatter by gms sync on {today.isoformat()}."',
        "tags: [meta, index, generated]",
        'data_vintage: "generated — never edit by hand; edit page frontmatter and rerun sync"',
        "sources: 0",
        f"updated: {today.isoformat()}",
        "---",
        "",
        "# index",
        "",
        f"**Generated by `python -m gms sync` on {today.isoformat()} — do not edit by hand.** "
        "Every row comes from the page's own `type:` / `summary:` / `data_asof:` frontmatter. "
        "The curated map is [[Global Macro Brain]]; the rules are [[_Vault Schema & Conventions]].",
        "",
    ]
    for folder in sorted(by_folder):
        lines += [f"## {folder}", "", "| Page | Type | Summary | Data as-of |", "|---|---|---|---|"]
        for p in sorted(by_folder[folder], key=lambda p: p.name.lower()):
            lines.append(f"| {_link(p.name)} | {_cell(p.type)} | {_cell(p.summary)} | {_cell(p.data_asof)} |")
        lines.append("")
    lines += ["## By type", ""]
    order = list(vault.PAGE_TYPES) + sorted(t for t in by_type if t not in vault.PAGE_TYPES)
    for t in order:
        if t not in by_type:
            continue
        group = sorted(by_type[t], key=lambda p: p.name.lower())
        lines += [f"### {t} ({len(group)})", "", " · ".join(_link(p.name) for p in group), ""]

    records = [
        {
            "name": p.name,
            "title": p.title,
            "path": str(p.path.relative_to(brain)).replace("\\", "/"),
            "folder": p.folder,
            "type": p.type,
            "category": p.meta.get("category"),
            "summary": p.summary,
            "data_asof": p.data_asof,
            "updated": str(p.meta.get("updated")) if p.meta.get("updated") else None,
            "tags": p.meta.get("tags") or [],
        }
        for p in sorted(pages, key=lambda p: (p.folder, p.name.lower()))
    ]
    return "\n".join(lines), records


def main(brain: Path, today: date | None = None) -> int:
    text, records = build(brain, today)
    home = brain / "00 - Home"
    (home / "index.md").write_text(text, encoding="utf-8")
    (home / "brain_index.json").write_text(json.dumps(records, indent=1, ensure_ascii=False, default=str), encoding="utf-8")
    return len(records)
